### PR TITLE
Fixed token dumber for real this time

### PR DESCRIPTION
**Pull request by Revadike**
This works

### CODE REVIEW

**Comment by Revadike** [comment]
Does it need any changes? Why haven't you merged it yet @DoctorMcKay ?

**Comment by DoctorMcKay** [comment]
I greatly prefer that you don't change code style (e.g. replacing `let` with `const`).

**Comment by Revadike** [comment]
Replacing `let` with `const` is not a style change (replacing `var` with `let/const` is though). If you don't reassign a variable, you make it `const`, that should be trivial. 
Other than replacing the tabs and changing quotes, did I change anything else?

**Comment by Revadike** [comment]
I'm so confused about your quote style... Sometimes you do single and sometimes double. For example, here you use both in the same line: https://github.com/DoctorMcKay/node-steam-user/blob/70d1f38504bb2d14fec56e947f9866d8ce49780f/examples/databasedownloader.js#L23

**Comment by Revadike** [comment]
How about using ESLint? It's a really useful tool to enforce your personal style. Nowadays I use it for all my projects.

**Comment by Revadike** [comment]
Check out https://github.com/DoctorMcKay/node-steam-user/pull/184/commits/a9945625c8cb65de258ceccd45b1f6296c4f4e69
Better now?
Also, any possibility you will merge any of my pull requests within the next month? :)

**Comment by DoctorMcKay** [comment]
I use whatever kind of quotes I feel like, basically. And I respectfully disagree about using const not being style.

**Comment by Revadike** [comment]
Lol, alright then. I'll respect that, but I have no idea how to follow your style either.

**Comment by DoctorMcKay** [comment]
About the only style I insist on is:

- tabs for indentation
- `const` for imports
- capitalize first letter of required namespaces or classes, or all caps if it's an abbreviation
    - This seems to be a little atypical for Node.js, but it's consistent with JavaScript (e.g. there's `Math.random()` and `JSON.parse()` instead of `math.random()` and `json.parse()`, so require fs as `FS`, http as `HTTP`, and events as `Events`
- let for variable declarations, unless var is appropriate in that situation
- ALL_CAPS global consts
- Don't mess with existing style except to bring it into these guidelines

**Comment by Revadike** [comment]
If you use prettier + eslint, you don't even have to think about the site. It will be autoformatted according to your rules, onsave. Being strict improves readability and consistency. 

That said, I've replaced the `const` with `let` for everything that is non-import, making the file fully according to your styling.

I do encourage you to read about the benefits of using `const` over `let`: https://medium.com/dailyjs/use-const-and-make-your-javascript-code-better-aac4f3786ca1 (or google it yourself)

**Comment by Revadike** [comment]
In time, I've actually changed my mind over the use of `const`. I now agree with your view as well.

**Pull request closed without merging**
