### PR TITLE
Fix #109 and #50

### LINKED ISSUE #50: Error: Parse error at line 1: unexpected ''
Hi.
I install steam-user using "npm install steam-user" and I use basic example but I have an error.
Thanks for help :)

zrzut ekranu z 2016-01-12 21 18 04

### LINKED ISSUE #109: Protobuf error - Error: Parse error at line 1: unexpected '
> /nodesteamuser/node_modules/protobufjs/dist/protobuf.js:784
>                 throw e;
>                 ^
> Error: Parse error at line 1: unexpected '

That character at the end is ETX.

I tried:
- reinstalling everything 10 times,
- basicbot.js example,
- different node versions,
- installing manually,
- copy-pasting protobufs from this git,
- [this fix](https://github.com/systemmovie/node-steam-user/commit/02920915c30173d8db5de9acdee6c2b82bbb7236) (It 'works' but doesn't even log in).

Something must be broken.

### PR DESCRIPTION
**Pull request by welwood08**
I just updated to the latest version and hit #109 again - any chance this fix can be integrated?

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
If we're going to go this route it might be best to just make sure the entry ends in `.proto` rather than adding the overhead of `statSync` for each file (or in addition).

**Comment by welwood08** [comment]
The overhead on my system is ~3ms total (average of 10 runs). Is it guaranteed that the files will always have a `.proto` extension? (I'll need to start a new pull since I don't have access to this branch.)

**Comment by DoctorMcKay** [comment]
Yes, the protobuf files will always have a `.proto` extension.

**Comment by welwood08** [comment]
See #138

**Pull request closed without merging**
