### PR TITLE
Game code redeem function

### PR DESCRIPTION
**Pull request by Aareksio**
Added function to redeem game code on the account.

I had no idea how to parse `purchase_receipt_info`, tried VDF.parse but returned empty object.

The result of `CMsgClientPurchaseResponse ` response should look like this:
```
{
        "eresult": 1,
        "purchase_result_details": 0,
        "purchase_receipt_info": {
                "MessageObject": {
                        "TransactionID": {
                                "low": -5334622,
                                "high": 126961050,
                                "unsigned": true
                        },
                        "PaymentMethod": 1,
                        "PurchaseStatus": 1,
                        "ResultDetail": 0,
                        "BasePrice": 0,
                        "TotalDiscount": 0,
                        "Tax": 0,
                        "shipping": 0,
                        "CurrencyCode": 0,
                        "TransactionTime": 1446344467,
                        "PackageID": -1,
                        "LineItemCount": 1,
                        "lineitems": [
                                {
                                        "TransactionID": {
                                                "low": -5334622,
                                                "high": 126961050,
                                                "unsigned": true
                                        },
                                        "PackageID": 39041,
                                        "ItemDescription": "CT Special Forces"
                                }
                        ],
                        "ErrorHeadline": "",
                        "ErrorString": "",
                        "ErrorLinkText": "",
                        "ErrorLinkURL": ""
                }
        }
}
```

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
`purchase_receipt_info` is a binary KV MessageObject. You can use `binarykvparser` which is already included in steam-user.

**Comment by Aareksio** [comment]
Updated, now returns array of [apps objects](https://github.com/DoctorMcKay/node-steam-user#gamesplayedapps) as third argument (empty array if none).

**Comment by DoctorMcKay** [comment]
I don't like using `game_id` and `game_extra_info` for packages. Packages are not apps; they *contain* apps. You can't play a package.

**Comment by Aareksio** [comment]
Changed, now output is an object whose keys are package IDs, and values are package names.

**Comment by DoctorMcKay** [comment]
Sorry, this should be the last feedback. If I'm reading this code right, the `key` parameter should be an object of format `{"key": "XXXXX-XXXXX-XXXXX"}`, when it would make more sense to just take the key as a string and create an object internally that's turned into a protobuf.

**Comment by Aareksio** [comment]
I don't really know - it works how it is now, and that's how it's [here](https://github.com/DoctorMcKay/node-steam-user/blob/master/protobufs/steammessages_clientserver_2.proto#L437), at least I think so, kinda newbie.

**Comment by Ne3tCode** [comment]
@DoctorMcKay 
> If I'm reading this code right, the  key  parameter should be an object of format  {"key": "XXXXX-XXXXX-XXXXX"}

You right, but just `key` (as string) works too.
```javascript
packageList[pkg.PackageID] = pkg.ItemDescription;
```
Sometimes `pkg.PackageID` is `undefined`. I don't know why, but it is very strange.

PS: json-code from the first post is mine :stuck_out_tongue_winking_eye:

**Comment by DoctorMcKay** [comment]
I believe that just using a string works due to a side-effect of the protobuf protocol. I'd rather not rely on side-effects.

**Comment by Aareksio** [comment]
Right then, updated to match object format.

**Comment by DoctorMcKay** [comment]
I don't have any keys to test this with, so I'll just believe that it works. Thanks a bunch!

I'll push an update to npm later on today.

**Pull request merged**
