### PR TITLE
verify not anymous user for webLogOn

### PR DESCRIPTION
**Pull request by emars**
fixes the issues discussed [here](http://steamcommunity.com/groups/SteamRE/discussions/4/412447613560680515/?tscn=1456091133)

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
Two things:

1. I'd prefer that the Error just be thrown. Gives a better stack trace and the error event is more for network errors.
2. Check the steamID property's type instead of _logOnDetails.

**Comment by emars** [comment]
:+1:

**Comment by DoctorMcKay** [comment]
Please don't use magic numbers. Use `SteamID.Type.ANON_USER` instead.

Besides that, looks good.

**Comment by DoctorMcKay** [comment]
Sorry to nitpick (I didn't notice this before) but the indentation isn't consistent.

**Pull request closed without merging**
