### PR TITLE
Added optional boolean to GetProductInfo

### PR DESCRIPTION
**Pull request by Royalgamer06**
See https://github.com/DoctorMcKay/node-steam-user/issues/112 and commit messages

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
The code looks good besides the feedback I left and the changing of unrelated code style. I appreciate you doing this.

**Comment by Royalgamer06** [comment]
I tried to avoid it, but my editor didn't like it 👍 
I replaced spaces with tabs, as u wanted.

**Comment by Royalgamer06** [comment]
I had set all `inclTokens` booleans in existing `self.getProductInfo` and `this.getProductInfo` to `false` as before, but maybe you'd like them to be `true` now. Please check.

**Comment by Royalgamer06** [comment]
Well, it's been several months. Any progress on this?

**Comment by Royalgamer06** [comment]
Bump

**Pull request merged**
