### PR TITLE
Add requestRichPresence

### PR DESCRIPTION
**Pull request by itsjfx**
Hi there, I decided to implement this so this module has rich presence capabilities on par with the capabilities offered by node-steam: https://github.com/seishun/node-steam/tree/master/lib/handlers/rich_presence (and I needed to mark off an excuse for why I haven't moved a project from node-steam to node-steam-user)

There's one thing in the implementation that on second thoughts could be implemented differently. First of all if RP cannot be parsed by the parser (most likely because the user is not in the game), I decided to omit the SteamID entirely from the response. In my head I figured it would be easier for a user to check whether the key exists in the object, instead of checking if the keys in the response was > 0 or checking if a key exists. I suppose this can instead be implemented where the key is added to the response for that SteamID and the value is a blank object (user would have to check len of keys in the response), or just a falsy value (false, null).

Also I'm aware that getPersonas gives RP data, but as I'm sure you know that's only for friends and this method can be called on total strangers (non friends) which is very cool!

Here's an example of a response of me chilling in the CS:GO main menu:
```
{
	users: {
		'76561197993496553': {
			status: 'Playing CS:GO',
			version: '13762',
			time: '17.338300',
			'game:state': 'lobby',
			steam_display: '#display_Menu',
			connect: '+gcconnectGXXXXXXXX'
		}
	}
}
```

### CODE REVIEW

**Comment by DoctorMcKay** [comment]
Why not just use the rich presence data already present in the `user` event?

**Comment by itsjfx** [comment]
> Why not just use the rich presence data already present in the `user` event?

I've only seen this work with people who are friends with the bot. Whenever I use getPersonas on an account not friends with the bot and then catch the user and getPersonas callback I've noticed the rich_presence array to be empty.

When using this however I've found it to be foolproof and work everytime, even on people who have private profiles.

**Comment by DoctorMcKay** [comment]
I see. Okay.

I would prefer to also break the RP parsing code from processUser and apply it here as well to get the localized string.

**Comment by itsjfx** [comment]
Ah of course, in my haste I didn't even consider this, will do

**Comment by itsjfx** [comment]
Looking at the RP parsing code from processUser: https://github.com/DoctorMcKay/node-steam-user/blob/79e3fc2fb5ec0be6a26a2c076479dd9876a26f75/components/friends.js#L973 it doesn't look like the rich_presence values ever get modified correct? Here is the code and some sample output:

``` 
[
    {
      key: 'status',
      value: 'Offline Casual workshop/243702660/aim_botz'
    },
    { key: 'version', value: '13762' },
    { key: 'time', value: '50.807220' },
    { key: 'game:state', value: 'game' },
    { key: 'steam_display', value: '#display_GameWkshpMap' },
    { key: 'game:act', value: 'offline' },
    { key: 'game:mode', value: 'casual' },
    { key: 'game:map', value: 'workshop/243702660/aim_botz' },
    { key: 'game:server', value: 'offline' }
] 
```

**Comment by itsjfx** [comment]
Oh I think I get what you mean, use the same implementation you use for parsing the RP string and apply it to all the properties for in the RP object we get now.

**Comment by DoctorMcKay** [comment]
Yeah, the parsing code doesn't actually modify any of the RP values, it just uses them to determine the localized string displayed in the client.

Since RP keys can be anything, I don't think that simply adding a `localized_string` property (or whatever) to the object you're returning is 100% foolproof, but maybe it's fine to do.

**Comment by itsjfx** [comment]
How's this, the response from requestRichPresence will look like this:
```
{
	"users": {
		"76561197993496553": {
			"RP": {
				"status": "Playing CS:GO",
				"version": "13762",
				"time": "17.367492",
				"game:state": "lobby",
				"steam_display": "#display_Menu",
				"connect": "+gcconnectG01FB0FE9"
			},
			"localizedString": "Playing CS:GO"
		}
	}
}
```

and the original behaviour from processUser is still maintained:

```
{
	rich_presence: [{
			key: 'status',
			value: 'Playing CS:GO'
		},
		{
			key: 'version',
			value: '13762'
		},
		{
			key: 'time',
			value: '17.367492'
		},
		{
			key: 'game:state',
			value: 'lobby'
		},
		{
			key: 'steam_display',
			value: '#display_Menu'
		},
		{
			key: 'connect',
			value: '+gcconnectG01FB0FE9'
		}
	],
	rich_presence_string: 'Playing CS:GO'
}
```

I made a helper function called _getRPLocalizedString for this.

**Comment by elf-pavlik** [comment]
I was getting empty presence using approach discussed in https://dev.doctormckay.com/topic/2474-rich-presence/

After testing method added by this branch, which requires setting appID, I could get proper presence of contacts on my friends list.

**Comment by DoctorMcKay** [comment]
Released in 4.18.0.

**Pull request merged**
